// ═══════════════════════════════════════════════════════════
// ClauseLight Mobile — Mock Data
// ═══════════════════════════════════════════════════════════

const MOCK_CONTRACTS = [
  {
    id: "c001",
    title: "房屋租赁合同",
    type: "租赁合同",
    score: 35,
    riskLevel: "red",
    redCount: 3,
    yellowCount: 2,
    greenCount: 5,
    model: "deepseek-chat",
    createdAt: "2026-06-12 14:30",
    fullText: "房屋租赁合同\n\n合同编号：HT-2026-06120001\n...",
    clauses: [
      {
        id: "cl001",
        number: "第一条",
        title: "房屋基本情况",
        content: "甲方将其拥有完全产权的位于北京市朝阳区建国路88号的房屋出租给乙方使用。",
        riskLevel: "green",
        riskType: "",
        riskSummary: "",
        plainExplanation: "这条没什么问题，就是正常描述房子位置。",
        legalBasis: "",
        suggestedClause: "",
        severityScore: 1,
      },
      {
        id: "cl002",
        number: "第三条",
        title: "租金及支付方式",
        content: "1. 月租金为人民币 8,500 元整\n2. 逾期支付，每逾期一日，乙方应按月租金的 5% 向甲方支付滞纳金。\n3. 甲方有权在提前 3 日通知乙方的情况下单方面调整租金，调整幅度不受限制。",
        riskLevel: "red",
        riskType: "违约金过高",
        riskSummary: "滞纳金按日5%计算，远超法定标准",
        plainExplanation: "逾期一天就要多付一个月租金的5%，也就是425块。而且房东随时能涨价，你没辙。",
        legalBasis: "《民法典》第五百八十五条：约定的违约金过分高于造成的损失的，人民法院或者仲裁机构可以根据当事人的请求予以适当减少。",
        suggestedClause: "逾期支付的，每逾期一日，乙方应按月租金的 0.1% 向甲方支付滞纳金。租金调整需双方协商一致，提前30日书面通知。",
        severityScore: 9,
      },
      {
        id: "cl003",
        number: "第四条",
        title: "押金",
        content: "乙方应在签订本合同时一次性支付押金人民币 17,000 元整。租赁期满后，甲方在确认房屋无损坏后30个工作日内退还。",
        riskLevel: "yellow",
        riskType: "押金风险",
        riskSummary: "押金为两个月租金，退还条件不明确",
        plainExplanation: "押金要交两个月的租金，而且合同没说清楚什么时候退、怎么退。30个工作日也太久了。",
        legalBasis: "《民法典》第七百一十四条：承租人应当妥善保管租赁物，因保管不善造成租赁物毁损、灭失的，应当承担赔偿责任。",
        suggestedClause: "押金为一个月租金，甲方应在租赁期满且乙方完成退房验收后 7 个工作日内无息退还。",
        severityScore: 6,
      },
      {
        id: "cl004",
        number: "第五条",
        title: "房屋维护",
        content: "租赁期间，房屋及附属设施的日常维修保养由乙方负责，费用由乙方承担。",
        riskLevel: "yellow",
        riskType: "维修责任",
        riskSummary: "所有维修费用转嫁给承租方，不合理",
        plainExplanation: "房子本来就该房东修，这条把所有维修费用都推给你了。",
        legalBasis: "《民法典》第七百一十三条：承租人在租赁物需要维修时可以请求出租人在合理期限内维修。",
        suggestedClause: "房屋及附属设施的自然损耗由甲方负责维修，因乙方使用不当造成的损坏由乙方承担。",
        severityScore: 5,
      },
      {
        id: "cl005",
        number: "第六条",
        title: "合同解除",
        content: "任何一方提前解除合同，需提前60日书面通知对方，并支付相当于三个月租金的违约金。",
        riskLevel: "red",
        riskType: "解约条件苛刻",
        riskSummary: "违约金过高，解约通知期过长",
        plainExplanation: "要走的话提前两个月说，还要赔三个月租金，这加起来就是五个月，太狠了。",
        legalBasis: "《民法典》第五百八十五条第二款：约定的违约金过分高于造成的损失的，当事人可以请求人民法院或者仲裁机构予以减少。",
        suggestedClause: "任何一方提前解除合同，需提前30日书面通知对方，并支付相当于一个月租金的违约金。",
        severityScore: 8,
      },
      {
        id: "cl006",
        number: "第七条",
        title: "转租限制",
        content: "未经甲方书面同意，乙方不得将房屋转租、转借或以其他方式交由第三方使用。",
        riskLevel: "green",
        riskType: "",
        riskSummary: "",
        plainExplanation: "这条是标准条款，不让随便转租，正常。",
        legalBasis: "",
        suggestedClause: "",
        severityScore: 2,
      },
      {
        id: "cl007",
        number: "第八条",
        title: "争议解决",
        content: "因本合同引起的争议，双方应协商解决；协商不成的，任何一方均可向合同签订地人民法院提起诉讼。",
        riskLevel: "green",
        riskType: "",
        riskSummary: "",
        plainExplanation: "标准争议解决条款，没什么问题。",
        legalBasis: "",
        suggestedClause: "",
        severityScore: 1,
      },
      {
        id: "cl008",
        number: "第九条",
        title: "房屋用途",
        content: "乙方租赁该房屋仅限用于居住，不得用于办公、经营或存放危险物品。",
        riskLevel: "green",
        riskType: "",
        riskSummary: "",
        plainExplanation: "规定只能住人，不能当办公室或仓库，正常。",
        legalBasis: "",
        suggestedClause: "",
        severityScore: 1,
      },
      {
        id: "cl009",
        number: "第十条",
        title: "水电费用",
        content: "租赁期间产生的水费、电费、燃气费、物业管理费由乙方承担，按实际使用量缴纳。",
        riskLevel: "green",
        riskType: "",
        riskSummary: "",
        plainExplanation: "水电燃气物业费你自己交，这很合理。",
        legalBasis: "",
        suggestedClause: "",
        severityScore: 1,
      },
      {
        id: "cl010",
        number: "第十一条",
        title: "甲方单方涨租",
        content: "甲方有权在租赁期内根据市场行情调整租金，调整幅度不超过上一年度CPI涨幅的3倍，乙方应在收到通知后15日内补缴差额。",
        riskLevel: "red",
        riskType: "单方涨租",
        riskSummary: "房东可单方面涨租，租户被迫接受",
        plainExplanation: "房东说涨就涨，你只能认了。CPI涨3倍基本上年年都能涨。",
        legalBasis: "《民法典》第五百四十三条：当事人协商一致，可以变更合同。",
        suggestedClause: "租金调整需双方协商一致，任何一方不得单方面调整。如遇特殊情况需调整，应提前60日书面通知并经双方同意。",
        severityScore: 8,
      },
    ],
  },
  {
    id: "c002",
    title: "劳动合同",
    type: "劳动合同",
    score: 72,
    riskLevel: "green",
    redCount: 1,
    yellowCount: 1,
    greenCount: 8,
    model: "deepseek-chat",
    createdAt: "2026-06-10 09:15",
  },
  {
    id: "c003",
    title: "软件外包服务合同",
    type: "外包合同",
    score: 58,
    riskLevel: "yellow",
    redCount: 1,
    yellowCount: 3,
    greenCount: 6,
    model: "deepseek-chat",
    createdAt: "2026-05-28 16:45",
  },
  {
    id: "c004",
    title: "装修施工合同",
    type: "装修合同",
    score: 45,
    riskLevel: "red",
    redCount: 2,
    yellowCount: 2,
    greenCount: 6,
    model: "deepseek-chat",
    createdAt: "2026-05-15 10:20",
  },
  {
    id: "c005",
    title: "设备采购合同",
    type: "采购合同",
    score: 81,
    riskLevel: "green",
    redCount: 0,
    yellowCount: 2,
    greenCount: 8,
    model: "deepseek-chat",
    createdAt: "2026-04-20 11:30",
  },
];

const MOCK_RULES = [
  {
    id: "r001",
    category: "通用",
    ruleText: "违约金不得超过实际损失的30%，超过部分可能被法院认定为无效。实际损失的认定需综合考虑合同履行情况、当事人过错程度等因素。",
    triggerKeywords: ["违约金", "赔偿"],
    riskLevel: "red",
    confidence: 0.9,
    source: "manual",
    usageCount: 12,
  },
  {
    id: "r002",
    category: "租赁",
    ruleText: "押金退还期限不应超过退房验收后15个工作日。押金金额一般不超过两个月租金。",
    triggerKeywords: ["押金", "退还"],
    riskLevel: "yellow",
    confidence: 0.8,
    source: "auto_learned",
    usageCount: 8,
  },
  {
    id: "r003",
    category: "劳动",
    ruleText: "试用期最长不得超过6个月，且试用期工资不得低于正式工资的80%。同一用人单位与同一劳动者只能约定一次试用期。",
    triggerKeywords: ["试用期", "工资"],
    riskLevel: "yellow",
    confidence: 0.95,
    source: "manual",
    usageCount: 15,
  },
  {
    id: "r004",
    category: "通用",
    ruleText: '合同中关于"最终解释权归甲方所有"的条款无效。根据《消费者权益保护法》，格式条款的解释应按照通常理解予以解释。',
    triggerKeywords: ["解释权", "格式条款"],
    riskLevel: "red",
    confidence: 0.85,
    source: "auto_learned",
    usageCount: 6,
  },
  {
    id: "r005",
    category: "租赁",
    ruleText: "出租人应当在租赁物交付时确保房屋符合安全使用条件。租赁期间房屋出现安全隐患，出租人应在合理期限内维修。",
    triggerKeywords: ["维修", "安全"],
    riskLevel: "green",
    confidence: 0.9,
    source: "manual",
    usageCount: 4,
  },
  {
    id: "r006",
    category: "外包",
    ruleText: "软件外包合同应明确约定交付物标准、验收流程和付款节点。建议设置分阶段付款，每阶段验收合格后支付。",
    triggerKeywords: ["交付", "验收", "付款"],
    riskLevel: "yellow",
    confidence: 0.8,
    source: "manual",
    usageCount: 3,
  },
];

const MOCK_LAWS = [
  {
    id: "l001",
    name: "《中华人民共和国民法典》",
    shortName: "民法典",
    articleCount: 1260,
    tags: ["合同", "民事", "通用"],
  },
  {
    id: "l002",
    name: "《中华人民共和国劳动合同法》",
    shortName: "劳动合同法",
    articleCount: 98,
    tags: ["劳动", "用工"],
  },
];

const MOCK_CONNECTION = {
  status: "connected",
  serverName: "我的电脑",
  serverIp: "192.168.1.100",
};

const ANALYSIS_STEPS = [
  { key: "ocr", label: "OCR" },
  { key: "split", label: "拆解" },
  { key: "analyze", label: "分析" },
  { key: "suggest", label: "建议" },
  { key: "score", label: "评分" },
];

// Export to window so other script files can access these
Object.assign(window, {
  MOCK_CONTRACTS, MOCK_RULES, MOCK_LAWS, MOCK_CONNECTION, ANALYSIS_STEPS,
});
