"""contractops foundation

Revision ID: 20260909_0001
Revises: 
Create Date: 2026-09-09 17:31:59.690510
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260909_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('raw_result', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('processing_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_table('asset_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_audit_log'))
    )
    op.create_index(op.f('ix_asset_audit_log_asset_id'), 'asset_audit_log', ['asset_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_id'), 'audit_events', ['resource_id'], unique=False)
    op.create_table('clause_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('clause_number', sa.String(), nullable=True),
    sa.Column('clause_title', sa.String(), nullable=True),
    sa.Column('clause_content', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_type', sa.String(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('plain_explanation', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('suggested_clause', sa.Text(), nullable=True),
    sa.Column('can_negotiate', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.String(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('source_start', sa.Integer(), nullable=True),
    sa.Column('source_end', sa.Integer(), nullable=True),
    sa.Column('citation_ids', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clause_analyses'))
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches')),
    sa.UniqueConstraint('source_sha256', name=op.f('uq_import_batches_source_sha256'))
    )
    op.create_table('knowledge_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('trigger_keywords', sa.Text(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('confirm_count', sa.Integer(), nullable=True),
    sa.Column('reject_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_rules'))
    )
    op.create_table('legal_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('law_name', sa.String(), nullable=False),
    sa.Column('article_number', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_references'))
    )
    op.create_table('memory_atoms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('confirm_count', sa.Integer(), nullable=True),
    sa.Column('reject_count', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('acl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_atoms'))
    )
    op.create_table('memory_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_events'))
    )
    op.create_index(op.f('ix_memory_events_session_id'), 'memory_events', ['session_id'], unique=False)
    op.create_table('memory_personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('acl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_personas'))
    )
    op.create_table('memory_scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('atom_ids', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('acl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_scenarios'))
    )
    op.create_table('memory_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_sessions'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('event_id', name='uq_outbox_events_event_id')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_organization_id'), 'outbox_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_type', sa.String(length=80), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('current_step', sa.String(length=80), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs')),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_processing_jobs_org_idempotency')
    )
    op.create_index(op.f('ix_processing_jobs_job_type'), 'processing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_processing_jobs_organization_id'), 'processing_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('triggers', sa.Text(), nullable=True),
    sa.Column('steps', sa.Text(), nullable=True),
    sa.Column('validation', sa.Text(), nullable=True),
    sa.Column('resources', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('acl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_table('sync_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sync_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_log'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('wiki_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_page_id', sa.String(), nullable=False),
    sa.Column('to_page_id', sa.String(), nullable=False),
    sa.Column('rel', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_links'))
    )
    op.create_index(op.f('ix_wiki_links_from_page_id'), 'wiki_links', ['from_page_id'], unique=False)
    op.create_index(op.f('ix_wiki_links_to_page_id'), 'wiki_links', ['to_page_id'], unique=False)
    op.create_table('wiki_pages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('acl_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages')),
    sa.UniqueConstraint('slug', name=op.f('uq_wiki_pages_slug'))
    )
    op.create_table('worker_risk_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('clause_number', sa.String(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_type', sa.String(), nullable=True),
    sa.Column('issue', sa.Text(), nullable=True),
    sa.Column('unfavorable_to', sa.String(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('citation_ids', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_risk_results'))
    )
    op.create_index(op.f('ix_worker_risk_results_analysis_id'), 'worker_risk_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_worker_risk_results_clause_number'), 'worker_risk_results', ['clause_number'], unique=False)
    op.create_table('api_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_credentials_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credentials'))
    )
    op.create_index(op.f('ix_api_credentials_key_prefix'), 'api_credentials', ['key_prefix'], unique=True)
    op.create_index(op.f('ix_api_credentials_organization_id'), 'api_credentials', ['organization_id'], unique=False)
    op.create_table('contract_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('contract_type', sa.String(length=80), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_records_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_records'))
    )
    op.create_index(op.f('ix_contract_records_organization_id'), 'contract_records', ['organization_id'], unique=False)
    op.create_table('job_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_job_steps_job_id_processing_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_steps')),
    sa.UniqueConstraint('job_id', 'step_key', name='uq_job_steps_job_key')
    )
    op.create_index(op.f('ix_job_steps_job_id'), 'job_steps', ['job_id'], unique=False)
    op.create_table('legacy_id_maps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('legacy_id', sa.String(length=120), nullable=False),
    sa.Column('new_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_legacy_id_maps_batch_id_import_batches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_id_maps')),
    sa.UniqueConstraint('batch_id', 'entity_type', 'legacy_id', name='uq_legacy_id_maps_source')
    )
    op.create_index(op.f('ix_legacy_id_maps_batch_id'), 'legacy_id_maps', ['batch_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_memberships_organization_id'))
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract_records.id'], name=op.f('fk_contract_versions_contract_id_contract_records')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_versions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_versions')),
    sa.UniqueConstraint('contract_id', 'version_number', name='uq_contract_versions_contract_number')
    )
    op.create_index(op.f('ix_contract_versions_content_sha256'), 'contract_versions', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_contract_versions_contract_id'), 'contract_versions', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_versions_organization_id'), 'contract_versions', ['organization_id'], unique=False)
    op.create_table('contract_clauses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_start', sa.Integer(), nullable=False),
    sa.Column('source_end', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], name=op.f('fk_contract_clauses_contract_version_id_contract_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_clauses_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_clauses')),
    sa.UniqueConstraint('contract_version_id', 'ordinal', name='uq_contract_clauses_version_ordinal')
    )
    op.create_index(op.f('ix_contract_clauses_content_sha256'), 'contract_clauses', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_contract_clauses_contract_version_id'), 'contract_clauses', ['contract_version_id'], unique=False)
    op.create_index(op.f('ix_contract_clauses_organization_id'), 'contract_clauses', ['organization_id'], unique=False)
    op.create_table('contract_parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], name=op.f('fk_contract_parties_contract_version_id_contract_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_contract_parties_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_parties')),
    sa.UniqueConstraint('contract_version_id', 'role', 'normalized_name', name='uq_contract_parties_version_role_name')
    )
    op.create_index(op.f('ix_contract_parties_contract_version_id'), 'contract_parties', ['contract_version_id'], unique=False)
    op.create_index(op.f('ix_contract_parties_normalized_name'), 'contract_parties', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_contract_parties_organization_id'), 'contract_parties', ['organization_id'], unique=False)
    op.create_table('document_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], name=op.f('fk_document_assets_contract_version_id_contract_versions')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_assets_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_assets_storage_key'))
    )
    op.create_index(op.f('ix_document_assets_content_sha256'), 'document_assets', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_document_assets_contract_version_id'), 'document_assets', ['contract_version_id'], unique=False)
    op.create_index(op.f('ix_document_assets_organization_id'), 'document_assets', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_assets_organization_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_contract_version_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_content_sha256'), table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index(op.f('ix_contract_parties_organization_id'), table_name='contract_parties')
    op.drop_index(op.f('ix_contract_parties_normalized_name'), table_name='contract_parties')
    op.drop_index(op.f('ix_contract_parties_contract_version_id'), table_name='contract_parties')
    op.drop_table('contract_parties')
    op.drop_index(op.f('ix_contract_clauses_organization_id'), table_name='contract_clauses')
    op.drop_index(op.f('ix_contract_clauses_contract_version_id'), table_name='contract_clauses')
    op.drop_index(op.f('ix_contract_clauses_content_sha256'), table_name='contract_clauses')
    op.drop_table('contract_clauses')
    op.drop_index(op.f('ix_contract_versions_organization_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_contract_id'), table_name='contract_versions')
    op.drop_index(op.f('ix_contract_versions_content_sha256'), table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_legacy_id_maps_batch_id'), table_name='legacy_id_maps')
    op.drop_table('legacy_id_maps')
    op.drop_index(op.f('ix_job_steps_job_id'), table_name='job_steps')
    op.drop_table('job_steps')
    op.drop_index(op.f('ix_contract_records_organization_id'), table_name='contract_records')
    op.drop_table('contract_records')
    op.drop_index(op.f('ix_api_credentials_organization_id'), table_name='api_credentials')
    op.drop_index(op.f('ix_api_credentials_key_prefix'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_index(op.f('ix_worker_risk_results_clause_number'), table_name='worker_risk_results')
    op.drop_index(op.f('ix_worker_risk_results_analysis_id'), table_name='worker_risk_results')
    op.drop_table('worker_risk_results')
    op.drop_table('wiki_pages')
    op.drop_index(op.f('ix_wiki_links_to_page_id'), table_name='wiki_links')
    op.drop_index(op.f('ix_wiki_links_from_page_id'), table_name='wiki_links')
    op.drop_table('wiki_links')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sync_log')
    op.drop_table('skills')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_organization_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_type'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_organization_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('memory_sessions')
    op.drop_table('memory_scenarios')
    op.drop_table('memory_personas')
    op.drop_index(op.f('ix_memory_events_session_id'), table_name='memory_events')
    op.drop_table('memory_events')
    op.drop_table('memory_atoms')
    op.drop_table('legal_references')
    op.drop_table('knowledge_rules')
    op.drop_table('import_batches')
    op.drop_table('contracts')
    op.drop_table('clause_analyses')
    op.drop_index(op.f('ix_audit_events_resource_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_asset_audit_log_asset_id'), table_name='asset_audit_log')
    op.drop_table('asset_audit_log')
    op.drop_table('analyses')
    # ### end Alembic commands ###
